let x;
let y;
let z;
let a;
let b;
x = 1 + 1 * 2;
y = (1 + 1) * 2;
z = 1 + 1 * 2;
a = 1 + (1 * 2) / 2;
b = (1 + 1 * 2) / 2;
console.log("The new value of x is: " + x);
console.log("The new value of y is: " + y);
console.log("The new value of z is: " + z);
console.log("The new value of a is: " + a);
console.log("The new value of b is: " + b);